/*
 * PinArt Labels MS
 *
 * A labels microservice for PinArt system.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package label

type ModelError struct {
	Code int64 `json:"code,omitempty"`

	Message string `json:"message"`
}
