---
swagger: "2.0"
info:
  description: "A labels microservice for PinArt system."
  version: "1.0.0"
  title: "PinArt Labels MS"
schemes:
- "http"
consumes:
- "application/io.goswagger.examples.todo-list.v1+json"
produces:
- "application/io.goswagger.examples.todo-list.v1+json"
paths:
  /label:
    get:
      tags:
      - "label"
      description: "Returns the available label"
      operationId: "getLabel"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "Id"
      - name: "since"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
        x-exportParamName: "Since"
        x-optionalDataType: "Int64"
      - name: "limit"
        in: "query"
        required: false
        type: "integer"
        default: 20
        format: "int32"
        x-exportParamName: "Limit"
        x-optionalDataType: "Int32"
      responses:
        "200":
          description: "label returned."
        default:
          description: "generic error response"
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
      - "label"
      description: "Updates the specified label."
      operationId: "updateLabel"
      parameters:
      - in: "body"
        name: "label"
        required: false
        schema:
          $ref: "#/definitions/label"
        x-exportParamName: "Label"
      responses:
        "202":
          description: "Label succesfully updated."
        default:
          description: "generic error response"
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
      - "label"
      description: "Creates a label."
      operationId: "addLabel"
      parameters:
      - in: "body"
        name: "label"
        required: false
        schema:
          $ref: "#/definitions/label"
        x-exportParamName: "Label"
      responses:
        "201":
          description: "Label succesfully created"
        default:
          description: "generic error response"
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
      - "label"
      description: "Deletes a label."
      operationId: "deleteLabel"
      parameters:
      - in: "body"
        name: "id"
        required: true
        schema:
          $ref: "#/definitions/id"
        x-exportParamName: "Id"
      responses:
        "202":
          description: "Label succesfully deleted"
        default:
          description: "generic error response"
          schema:
            $ref: "#/definitions/error"
definitions:
  id:
    type: "integer"
    format: "int64"
  label:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        minLength: 1
      description:
        type: "string"
        minLength: 1
      relatedLabels:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  error:
    type: "object"
    required:
    - "message"
    properties:
      code:
        type: "integer"
        format: "int64"
      message:
        type: "string"
