/*
 * PinArt Labels MS
 *
 * A labels microservice for PinArt system.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	_ "github.com/go-sql-driver/mysql"
)

func dbConn() (db *sql.DB) {
	dbDriver := "mysql"
	dbUser := "labelms"
	dbPass := "2020i"
	dbName := "tcp(pinart-labels-db:3306)/labels" //"tcp(127.0.0.1:3307)/labels"
	db, err := sql.Open(dbDriver, dbUser+":"+dbPass+"@"+dbName)
	if err != nil {
		log.Panic(err.Error())
		panic(err.Error())
	}
	return db
}

func AddLabel(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	db := dbConn()
	body, err := ioutil.ReadAll(r.Body)
	defer r.Body.Close()
	if err != nil {
		log.Printf("Error reading body: %v", err)
		http.Error(w, "can't read body", http.StatusBadRequest)
		return
	}
	fmt.Printf("%s", body)
	var theLabel Label
	err = json.Unmarshal(body, &theLabel)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	insForm, err := db.Prepare("INSERT INTO Label(name, description) VALUES(?,?)")
	if err != nil {
		panic(err.Error())
	}
	result, err := insForm.Exec(theLabel.Name, theLabel.Description)
	if err != nil {
		panic(err.Error())
	}
	fmt.Println(result)
	w.WriteHeader(http.StatusCreated)
}

func DeleteLabel(w http.ResponseWriter, r *http.Request) {

	db := dbConn()

	body, err := ioutil.ReadAll(r.Body)
	defer r.Body.Close()
	if err != nil {
		log.Printf("Error reading body: %v", err)
		http.Error(w, "can't read body", http.StatusBadRequest)
		return
	}
	fmt.Printf("%s", body)
	var theLabel Label
	err = json.Unmarshal(body, &theLabel)

	delete, err := db.Prepare("DELETE FROM Label WHERE idLabel=?")
	if err != nil {
		panic(err.Error())
	}
	delete.Exec(theLabel.Id)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusAccepted)
}

func GetLabel(w http.ResponseWriter, r *http.Request) {

	db := dbConn()
	id := r.URL.Query().Get("id")
	results, err := db.Query("SELECT name, description FROM Label WHERE idLabel=?", id)

	if err != nil {
		panic(err.Error())
	}
	var lab Label
	for results.Next() {

		// for each row, scan the result into our tag composite object
		err = results.Scan(&lab.Name, &lab.Description)
		if err != nil {
			panic(err.Error()) // proper error handling instead of panic in your app
		}
	}
	js, err := json.Marshal(lab)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	w.Write(js)
}

func UpdateLabel(w http.ResponseWriter, r *http.Request) {

	db := dbConn()

	body, err := ioutil.ReadAll(r.Body)
	defer r.Body.Close()
	if err != nil {
		log.Printf("Error reading body: %v", err)
		http.Error(w, "can't read body", http.StatusBadRequest)
		return
	}
	fmt.Printf("%s", body)
	var theLabel Label
	err = json.Unmarshal(body, &theLabel)

	update, err := db.Prepare("UPDATE Label SET name=?, description=? WHERE idLabel=?")
	if err != nil {
		panic(err.Error())
	}
	update.Exec(theLabel.Name, theLabel.Description, theLabel.Id)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusAccepted)
}
